language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://riglesias-free-now.pact.dius.com.au/
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "lx9BLrvpiUhHOhqpdXeyYYq6taBh2BqdBtPbGsprnc8TAQNwhgcK261gpepdwF07OtKV9GwlalRVnarYesaSUSZTdVBbounH4myCIUtGf8Som0ClgdtCv+MrGo4hcm0Nnmjre1F7MRShi3ZjPw53s+rvOdY4lb/rYDOwEw4qMI0UfDyhVvJqTkvep/hDDBNo90T+9racnAijue5tPH0YeyYd0mUbN5ysQVYGIuBrfoKY92q9Tsi6VBK5N3aeL/RyZtPP2OCG1gEpMFKD4mn31qq0eRvrUTNhn1e0BXztfm1fLydIU1pNiE69Ic3mSz0IJv3F5vBPWtNBRbGf0bPm5tWN+q+wRofafK2Pd+9GOuIYgt7EQxCXFb52sS9vBi7p/jHEycC8gZbh0IK7ugf+6v5Ct6bUfCmzLZsSudRShyoENDyPM8m4zAjNEoxJ5EmwoEDbGP7flnLIVwLsYA5qngiZWKSF8IGF2tjUtkTGBUm7KSqwK7uJL45c9NHHFSy6aojbHBWAgiEYdksBAWZCHDfWp4/wrTX9aRe4MII5bNr7ChhNPB0RsM4pu3jrZeQ6g0akEtbOSK1vx67g+NtjqDcU7+kSo7xaBzqFDPC+e80bTw0tKlxc8opaBEt5vpdUIaWgHYY5xSmnmSuI7o8NKgFuq5IORRxPPMR6oNjxQM8="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
